name: michael beachum
favicon: null
layout_spectrum: 0.33262
typography_spectrum: 0.3702
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0a0d'
    - '#342d27'
    - '#958671'
    - '#4d1514'
    - '#51483f'
  brandStrength: 0.0625
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
