name: michael beachum
favicon: null
layout_spectrum: 0.33262
typography_spectrum: 0.3702
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffeff'
    - '#0b090e'
    - '#7b6f57'
    - '#c2bac9'
    - '#377cfd'
  brandStrength: 0.0625
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
