name: michaelbeachum
favicon: null
layout_spectrum: 0.8019217511173338
typography_spectrum: 0.4954310469329357
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.07643393334001303
  lightness: 0.7668207983952016
  saturation: 0.03520064358599484
  rhythmicContrast: 0.1816101789008826
purpose: []
