layout_spectrum: 0.3812406493816525
typography_spectrum: 0.7261545287910849
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.5986290781293064
  lightness: 0.2742693133186549
  saturation: 0.09907613974064589
  rhythmicContrast: 0.4034377848729491
name: michael beachum
favicon: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
